## ---- 生产环境 ---- ##

# 端口设置
server:
  port: 8080

spring:
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    password: '123456'
    port: 6379

  # 数据库配置
  datasource:
    # 数据库连接池监控
    druid:
      stat-view-servlet:
        # 数据库监控开关
        enabled: false
        # 登录用户名/密码
        login-username: admin
        login-password: 123456
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow:
        # IP 黑名单，若白名单也存在，则优先使用
        deny:
    # 多数据源
    dynamic:
      #主数据源
      #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      #primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/opsli-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
          username: root
          password: 12345678
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 多数据源配置
          #slave-datasource:
          #url: jdbc:mysql://127.0.0.1:3306/opsli-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
          #username: root
          #password: 12345678
          #driver-class-name: com.mysql.cj.jdbc.Driver


# knife4j 文档 配置
knife4j:
  basic:
    ## 开启Swagger的Basic认证功能,默认是false
    enable: false
    ## Basic认证用户名
    username: admin
    ## Basic认证密码
    password: 123456

  # 是否生产环境 （生产环境默认屏蔽文档）
  production: true


# opsli 自定义配置
opsli:

  # 演示模式
  enable-demo: true

  # web 上传文件路径
  web:
    upload-path: /Users/system/Documents/work/tmp/opsli

# 系统日志
log:
  path: /var/log
